apiVersion: veecode.backstage.io/v1alpha1
kind: Cluster
metadata:
  name: "ec2abr"
  environment:
    cluster_type: ec2
  annotations:
    github.com/project-slug: veecode-homolog/ec2abr
    backstage.io/techdocs-ref: dir:.
    github.com/workflows: terraform-deploy.yml,start_instance.yml,stop_instance.yml,terraform-destroy.yml,deploy_dashboard
spec:
  type: ec2
  lifecycle: experimental
  owner: "group:default/admin"
  dependsOn: ["environment:default/ec2_environment"]
  
